package examples.java.awt;

import java.awt.AWTEvent;
import java.awt.Adjustable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.LayoutManager;
import java.awt.Scrollbar;
import java.awt.SystemTray;
import java.awt.TextField;
import java.awt.TransparencyOpacity;
import java.awt.WindowStateListener;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.BoundedRangeModel;
import javax.swing.ButtonGroup;
import javax.swing.Checkbox;
import javax.swing.ColorChooser;
import javax.swing.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.J2MePlayer;
import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowStateEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import javax.swing.event.WindowStateEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerEvent;
import java.awt.event.FocusEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ContainerEvent;
import javax.swing.event.FocusEvent;
import javax.swing.event.HierarchyEvent;
import javax.swing.event.HierarchyListener;
import javax.swing.event.MouseEvent;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuBar;
import java.awt.event.WindowStateEvent;
import javax.swing.JFrame;

public class SwingTest {

    private static final String WINDOW_TITLE = "Swing Test";
    private static JFrame frame;
    // Create a label to display a message
    private static JLabel label;
    // Create a combo box with options
    private static JComboBox<String> comboBox;

    public static void main(String[] args) {

        createSwingComponents();
        setLayOutProperties();
        addListenersToComponents();
        frame.pack();
        frame.setVisible(true));
    }

    private static void createSwingComponents() {
        // Create a frame to contain the components
        frame = new JFrame(WINDOW_TITLE));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE));
        // Create a label to display a message
        label = new JLabel("Hello, Swing!"));
        // Create a combo box with options
        String[] items = {"Option 1", "Option 2", "Option 3"};
        comboBox = new JComboBox<String>(items));
    }

    private static void setLayOutProperties() {
        frame.setLayout(new FlowLayout()));
        // Add the label and combo box to the frame
        frame.add(label);
        frame.add(comboBox);
    }

    private static void addListenersToComponents() {
        // Add a listener to the frame's window state property
        frame.addWindowStateListener(new WindowStateListener(){
            public void windowStateChanged(WindowStateEvent e) {
                // Check if the frame is maximized
                if (e.isMaximized()) {
                    label.setFont(new Font("Courier New", Font.BOLD | Font.ITALIC, 18))));
                }
            }
        }));
    }
}